#!/bin/bash

WWW_GROUP=www-data
PROJECT_DOCUMENT_ROOT=/path/to/project/document/root/


sudo chown WWW_GROUP:WWW_GROUP -R /PROJECT_DOCUMENT_ROOT/ 
sudo chown WWW_GROUP:WWW_GROUP -R /PROJECT_DOCUMENT_ROOT/.git
sudo chmod 777 -R /PROJECT_DOCUMENT_ROOT/
sudo chmod 770 -R /PROJECT_DOCUMENT_ROOT/.git
sudo chown WWW_GROUP: /PROJECT_DOCUMENT_ROOT/.git/hooks/*-receive
sudo chmod 750 /PROJECT_DOCUMENT_ROOT/.git/hooks/*-receive
cd /PROJECT_DOCUMENT_ROOT/
sudo git config core.filemode false
sudo git config receive.denyCurrentBranch ignore

sudo chown -R WWW_GROUP: -R /PROJECT_DOCUMENT_ROOT/.git
